// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using angularConnection.Data.Context;

#nullable disable

namespace angularConnection.Migrations
{
    [DbContext(typeof(devContext))]
    [Migration("20230510210145_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("angularConnection.Data.Model.Course", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("labHours")
                        .HasColumnType("int");

                    b.Property<int>("lecHours")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            id = 1,
                            labHours = 36,
                            lecHours = 36,
                            name = "C#"
                        },
                        new
                        {
                            id = 2,
                            labHours = 12,
                            lecHours = 12,
                            name = "node.js"
                        },
                        new
                        {
                            id = 3,
                            labHours = 18,
                            lecHours = 18,
                            name = "Angular"
                        },
                        new
                        {
                            id = 4,
                            labHours = 24,
                            lecHours = 24,
                            name = "MVC"
                        });
                });

            modelBuilder.Entity("angularConnection.Data.Model.Department", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Capacity = 50,
                            Name = "PD"
                        },
                        new
                        {
                            id = 2,
                            Capacity = 15,
                            Name = "AI"
                        },
                        new
                        {
                            id = 3,
                            Capacity = 25,
                            Name = "SA"
                        },
                        new
                        {
                            id = 4,
                            Capacity = 40,
                            Name = "OS"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
